# Generated by Django 2.1.7 on 2019-03-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_auto_20190323_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profileImage',
            field=models.ImageField(upload_to='static/product_img'),
        ),
    ]
