# Generated by Django 2.1.7 on 2019-03-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20190323_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
