# Generated by Django 2.1.7 on 2019-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_auto_20190323_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
