# Generated by Django 2.1.7 on 2019-03-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
    ]
